/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveShopRouteImport } from './routes/live-shop'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as LojasIndexRouteImport } from './routes/lojas.index'
import { Route as LojasStoreIdRouteImport } from './routes/lojas.$storeId'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosOrderIdRouteImport } from './routes/pedidos.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveShopRoute = LiveShopRouteImport.update({
  id: '/live-shop',
  path: '/live-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasIndexRoute = LojasIndexRouteImport.update({
  id: '/lojas/',
  path: '/lojas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasStoreIdRoute = LojasStoreIdRouteImport.update({
  id: '/lojas/$storeId',
  path: '/lojas/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosOrderIdRoute = PedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-shop': typeof LiveShopRoute
  '/produtos': typeof ProdutosRoute
  '/lojas/$storeId': typeof LojasStoreIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/lojas/': typeof LojasIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-shop': typeof LiveShopRoute
  '/produtos': typeof ProdutosRoute
  '/lojas/$storeId': typeof LojasStoreIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/lojas': typeof LojasIndexRoute
  '/pedidos': typeof PedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-shop': typeof LiveShopRoute
  '/produtos': typeof ProdutosRoute
  '/lojas/$storeId': typeof LojasStoreIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/lojas/': typeof LojasIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live-shop'
    | '/produtos'
    | '/lojas/$storeId'
    | '/pedidos/$orderId'
    | '/lojas/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live-shop'
    | '/produtos'
    | '/lojas/$storeId'
    | '/pedidos/$orderId'
    | '/lojas'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/live-shop'
    | '/produtos'
    | '/lojas/$storeId'
    | '/pedidos/$orderId'
    | '/lojas/'
    | '/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveShopRoute: typeof LiveShopRoute
  ProdutosRoute: typeof ProdutosRoute
  LojasStoreIdRoute: typeof LojasStoreIdRoute
  PedidosOrderIdRoute: typeof PedidosOrderIdRoute
  LojasIndexRoute: typeof LojasIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-shop': {
      id: '/live-shop'
      path: '/live-shop'
      fullPath: '/live-shop'
      preLoaderRoute: typeof LiveShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas/': {
      id: '/lojas/'
      path: '/lojas'
      fullPath: '/lojas/'
      preLoaderRoute: typeof LojasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas/$storeId': {
      id: '/lojas/$storeId'
      path: '/lojas/$storeId'
      fullPath: '/lojas/$storeId'
      preLoaderRoute: typeof LojasStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$orderId': {
      id: '/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof PedidosOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveShopRoute: LiveShopRoute,
  ProdutosRoute: ProdutosRoute,
  LojasStoreIdRoute: LojasStoreIdRoute,
  PedidosOrderIdRoute: PedidosOrderIdRoute,
  LojasIndexRoute: LojasIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
