/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as LiveShopRouteImport } from './routes/live-shop'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as FornecedoresIndexRouteImport } from './routes/fornecedores.index'
import { Route as FornecedoresSupplierIdRouteImport } from './routes/fornecedores.$supplierId'
import { Route as LojasIndexRouteImport } from './routes/lojas.index'
import { Route as LojasStoreIdRouteImport } from './routes/lojas.$storeId'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosOrderIdRouteImport } from './routes/pedidos.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveShopRoute = LiveShopRouteImport.update({
  id: '/live-shop',
  path: '/live-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresIndexRoute = FornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresSupplierIdRoute = FornecedoresSupplierIdRouteImport.update({
  id: '/fornecedores/$supplierId',
  path: '/fornecedores/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasIndexRoute = LojasIndexRouteImport.update({
  id: '/lojas/',
  path: '/lojas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasStoreIdRoute = LojasStoreIdRouteImport.update({
  id: '/lojas/$storeId',
  path: '/lojas/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosOrderIdRoute = PedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/funil': typeof FunilRoute
  '/live-shop': typeof LiveShopRoute
  '/produtos': typeof ProdutosRoute
  '/fornecedores/$supplierId': typeof FornecedoresSupplierIdRoute
  '/lojas/$storeId': typeof LojasStoreIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/fornecedores/': typeof FornecedoresIndexRoute
  '/lojas/': typeof LojasIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/funil': typeof FunilRoute
  '/live-shop': typeof LiveShopRoute
  '/produtos': typeof ProdutosRoute
  '/fornecedores/$supplierId': typeof FornecedoresSupplierIdRoute
  '/lojas/$storeId': typeof LojasStoreIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/fornecedores': typeof FornecedoresIndexRoute
  '/lojas': typeof LojasIndexRoute
  '/pedidos': typeof PedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/funil': typeof FunilRoute
  '/live-shop': typeof LiveShopRoute
  '/produtos': typeof ProdutosRoute
  '/fornecedores/$supplierId': typeof FornecedoresSupplierIdRoute
  '/lojas/$storeId': typeof LojasStoreIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/fornecedores/': typeof FornecedoresIndexRoute
  '/lojas/': typeof LojasIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/estoque'
    | '/financeiro'
    | '/funil'
    | '/live-shop'
    | '/produtos'
    | '/fornecedores/$supplierId'
    | '/lojas/$storeId'
    | '/pedidos/$orderId'
    | '/fornecedores/'
    | '/lojas/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/estoque'
    | '/financeiro'
    | '/funil'
    | '/live-shop'
    | '/produtos'
    | '/fornecedores/$supplierId'
    | '/lojas/$storeId'
    | '/pedidos/$orderId'
    | '/fornecedores'
    | '/lojas'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/estoque'
    | '/financeiro'
    | '/funil'
    | '/live-shop'
    | '/produtos'
    | '/fornecedores/$supplierId'
    | '/lojas/$storeId'
    | '/pedidos/$orderId'
    | '/fornecedores/'
    | '/lojas/'
    | '/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FunilRoute: typeof FunilRoute
  LiveShopRoute: typeof LiveShopRoute
  ProdutosRoute: typeof ProdutosRoute
  FornecedoresSupplierIdRoute: typeof FornecedoresSupplierIdRoute
  LojasStoreIdRoute: typeof LojasStoreIdRoute
  PedidosOrderIdRoute: typeof PedidosOrderIdRoute
  FornecedoresIndexRoute: typeof FornecedoresIndexRoute
  LojasIndexRoute: typeof LojasIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-shop': {
      id: '/live-shop'
      path: '/live-shop'
      fullPath: '/live-shop'
      preLoaderRoute: typeof LiveShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/': {
      id: '/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof FornecedoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/$supplierId': {
      id: '/fornecedores/$supplierId'
      path: '/fornecedores/$supplierId'
      fullPath: '/fornecedores/$supplierId'
      preLoaderRoute: typeof FornecedoresSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas/': {
      id: '/lojas/'
      path: '/lojas'
      fullPath: '/lojas/'
      preLoaderRoute: typeof LojasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas/$storeId': {
      id: '/lojas/$storeId'
      path: '/lojas/$storeId'
      fullPath: '/lojas/$storeId'
      preLoaderRoute: typeof LojasStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$orderId': {
      id: '/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof PedidosOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  FunilRoute: FunilRoute,
  LiveShopRoute: LiveShopRoute,
  ProdutosRoute: ProdutosRoute,
  FornecedoresSupplierIdRoute: FornecedoresSupplierIdRoute,
  LojasStoreIdRoute: LojasStoreIdRoute,
  PedidosOrderIdRoute: PedidosOrderIdRoute,
  FornecedoresIndexRoute: FornecedoresIndexRoute,
  LojasIndexRoute: LojasIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
